In [7]:
import numpy as np
import time

print(f'Showing how vectorization speed up product vetor')

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print(f'Vectorized version: {1000*(toc-tic)}ms')

tic = time.time()
c = 0
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print(f'For loop: {1000*(toc-tic)}ms')

Showing how vectorization speed up product vetor
249515.6810027159
Vectorized version: 1.2209415435791016ms
249515.6810027138
For loop: 327.5144100189209ms


In [6]:
import numpy as np

print(f'Broacasting with numpy treats arrays with different dimensions')

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

cal = A.sum(axis=0)
print(cal)

percentage = 100 * A / cal.reshape(1,4)
print(percentage)

[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
a = np.random.rand(2,3)
a.shape

(2, 3)

In [10]:
b = np.random.rand(2,1)
b.shape

(2, 1)

In [12]:
c = a + b
c.shape

(2, 3)

In [13]:
a = np.random.rand(4,3)
a.shape

(4, 3)

In [14]:
b = np.random.rand(2,1)
b.shape

(2, 1)

In [16]:
c = a * b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (2,1) 

In [20]:
a = np.random.rand(12288,150)
print(a.shape)
b = np.random.rand(150,45)
print(b.shape)
c = np.dot(a,b)
print(c.shape)

(12288, 150)
(150, 45)
(12288, 45)


In [21]:
a = np.random.rand(3,3)
print(a.shape)
b = np.random.rand(3,1)
print(b.shape)
c = a*b
print(c.shape)

(3, 3)
(3, 1)
(3, 3)
